# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='spread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
